server:
  port: 8081
spring:
  application:
    name: Ohoho-Item-Service
  datasource:
    url: jdbc:mysql://106.15.248.243:3306/ohoho
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1